language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"
install: "pip install -r requirements-dev.txt"
script: pytest tests.py
# deploy:
#   provider: pypi
#   user: __token__
#   password:
#     secure:
#   distributions: sdist bdist_wheel
#   skip_existing: true
#   skip_cleanup: true
#   on:
#     branch: master
